# STOCK/CRPYTO PRICE PREDICTION MODEL

## The following code is an example on how to use simple data analysis tolls in order to set up a simple strategy for long and short term financial trading

### We will make use of the programing language python (3.x) which suits nicely for data anlysis

## --> This a very is simplified model for trading. One should always invest just as much money as one can afford to loose and do own studies in advance. 

## Required modules:
- numpy: the code is designed to be vectorized such that the numpy module can be used and calculations performed fast
- pandas: module for illustrative data frames
- yfinance: api module provided by yahoo finance to get current and previous asset prices
- matplotlib: (sub)module(s) for plots
- scipy: (sub)module for statistical and signal analysis
- datetime: (optional)

In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from model import MODEL
import utils

In [281]:
tickers = ['BTC-USD', 'LTC-USD']
tickers = 'LTC-USD'
model = MODEL(tickers=tickers)

In [282]:
start_date = '2020-01-01'
model.get_data(start=start_date, interval='60m', threads=1)

[*********************100%***********************]  1 of 1 completed


In [283]:
date_range = utils.create_date_range(start_date=start_date, freq='3h')
model.apply_date_filter(date_range)

[INFO]: filter applied.


In [295]:
model._init_model()

822


In [293]:
model.grad['LTC-USD']

numpy.float64

In [220]:
#ltc grad
model.grad[-10:]

array([0.04653898, 0.03381959, 0.02575402, 0.04243673, 0.04099117,
       0.02041081, 0.03172823, 0.04473742, 0.05003016, 0.05812485])

In [214]:
#btc grad
model.grad[-10:]

array([3.56094197, 1.92102105, 3.24438772, 6.420627  , 5.0443031 ,
       2.77423147, 3.71035544, 5.21641727, 7.93910375, 9.73290095])

In [219]:
#ltc mins
model.local_min

array([  3,   6,   9,  14,  23,  25,  28,  34,  39,  45,  49,  52,  62,
        67,  70,  74,  83,  87,  91,  94,  97, 100, 107, 114, 117, 120,
       127, 132, 138, 141, 148, 155, 159, 162, 165, 168, 176, 181, 186,
       192, 196, 201, 204, 210, 215, 221, 228, 232, 244, 252, 256, 266,
       275, 278, 288, 290, 294, 300, 304, 308, 317, 322, 326, 328, 334,
       340, 343, 347, 351, 356, 361, 365, 373, 377, 379, 383, 387, 396,
       399, 403, 410, 415, 418, 422, 433, 437, 441, 445, 448, 453, 459,
       463, 467, 470, 476, 479, 482, 486, 492, 496, 498, 501, 508, 520,
       525, 529, 534, 536, 541, 549, 554, 557, 564, 572, 575, 581, 587,
       592, 595, 597, 602, 606, 615, 618, 625, 628, 632, 638, 642, 652,
       658, 665, 668, 673, 676, 682, 684, 692, 696, 707, 711, 721, 725,
       729, 733, 740, 743, 749, 753, 756, 762, 766, 772, 783, 788, 793,
       802, 811, 814, 817])

In [213]:
#btc mins
model.local_min

array([  3,   9,  14,  23,  28,  35,  39,  45,  52,  62,  70,  74,  78,
        84,  88,  94, 100, 107, 114, 120, 125, 132, 138, 141, 148, 155,
       162, 165, 172, 178, 186, 192, 195, 200, 204, 210, 213, 218, 221,
       228, 232, 243, 252, 256, 264, 268, 275, 278, 285, 288, 290, 294,
       299, 302, 304, 309, 318, 322, 328, 341, 343, 347, 350, 354, 362,
       365, 374, 377, 380, 387, 396, 399, 415, 418, 421, 430, 433, 438,
       441, 445, 448, 454, 459, 463, 467, 470, 476, 479, 482, 486, 498,
       501, 508, 513, 520, 525, 529, 534, 541, 548, 554, 557, 562, 565,
       572, 575, 581, 587, 592, 595, 597, 603, 607, 613, 615, 618, 625,
       628, 632, 638, 642, 652, 658, 661, 665, 669, 672, 676, 678, 682,
       692, 696, 701, 707, 711, 717, 723, 728, 732, 739, 744, 749, 756,
       762, 766, 774, 777, 783, 788, 793, 796, 802, 813, 817])